config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :users, only: [:edit, :update]
  resources :posts, only: [:index, :new, :create, :show] do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :text, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user 
  
  validates :text, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :posts
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_user

  def index
    # @comments = Comment.all
  end

  def new
    # @comment = Comment.new
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
    # @comment = @user.comments.new(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :image).merge(user_id: current_user.id,  post_id: params[:post_id])
  end

  # def set_user
  #   @user = User.find(params[:user_id])
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.all
    # @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end
  
  def create
    Post.create(post_params)
    # redirect_to root_path
  end

  def show
    @posts = Post.all
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end


  private
  def post_params
    params.require(:post).permit(:title, :image, :text).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id]) 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    -# = stylesheet_link_tag ‘application’, media: ‘all’
    -# = javascript_include_tag ‘application’
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Myfirst
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/posts/_comment.html.haml
.com{data: {post: {id: comment.id}}}
  .comStatus
    .comUserName
      = comment.name
    .comDate
      = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .comComments
    - if comment.text.present?
      %p.comContent
        = comment.text
    = image_tag comment.image.url, class: 'comImage' if comment.image.present?

app/views/posts/_main_message.html.haml
.main-message
  .main-message__tag-search
    = form_tag('/search', method: :get, class: 'main-message__tag-search__search-form') do
      %input.search-form__input{name: "keyword", placeholder: " 検索したい投稿を入力", type: "text", value: ""}
      %button.btn-search{title: "検索", type: "submit"}
        = icon('fas fa-search', class: "main-message__tag-search__search-form__icon")
  .main-message__contents
    -# = render 
  -#   .o3comments
  -#     %h4
  -#       ＜コメント一覧＞
  -#     - if @comments
  -#       - @comments.each do |comment|
  -#         %p
  -#           %strong
  -#             = link_to posts_path do
  -#               - comment.user.nickname
  -#         - comment.text




  -# .main-message__commentCreate
  -#   - if current_user
  -#     = form_with model: [@post, @comment], local: true do |f|
  -#       = f.text_field :text, placeholder: "コメントする", rows: "2"
  -#       = f.submit "SEND"
  -#   - else
  -#     %strong
  -#       %p
  -#         ※※※ コメントの投稿には新規登録/ログインが必要です ※※※

app/views/posts/_post.html.haml
.main-message__contents__message-box{data: {post: {id: post.id}}}
  .main-message__contents__message-box__status   
    .main-message__contents__message-box__status__user-name
      = post.title
    .main-message__contents__message-box__status__date
      = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .main-message__contents__message-box__posts
    - if post.text.present?
      %p.main-message__contents__message-box__posts__content
        = post.text
    = image_tag post.image.url, class: 'main-message__contents__message-box__posts__image' if post.image.present?

app/views/posts/_side_bar.html.haml
.side-bar
  .side-bar__status
    .side-bar__status__detail
      .side-bar__status__detail__name
        = current_user.name
      .side-bar__status__detail__icons
        .ui.animated.fade.button
          = link_to new_post_path do
            .visible.content
              新規投稿
            .hidden.content
              ここを
              %br クリック
        .ui.animated.fade.button
          = link_to edit_user_path(current_user) do
            .visible.content
              アカウント
              %br 管理
            .hidden.content
              ここを 
              %br クリック
  .side-bar__book-list
    投稿一覧
  - @posts.each do |post|
    = link_to post_path(id: post.id), class: "side-bar__book-list__detail" do
      %p
        = post.title




  -# = link_to post_path(id: @posts.ids), class: "side-bar__book-list__detail" do
  -#   - @posts.each do |post|
  -#     %p
  -#       = post.title

app/views/posts/create.html.haml
.contents-row
  .contents-row__success
    投稿が完了しました。
    = link_to posts_path(current_user), class: "contents-row__success__return" do
      投稿一覧へ戻る

app/views/posts/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_message"

app/views/posts/new.html.haml
.contents-row
  .contents-row__container
    = form_for @post do |form|
      投稿する
      .field
        .field-input
          = form.text_field :title, placeholder: " Title", autofocus: true
          = form.file_field :image, class: 'hidden'
          = form.text_field :text, placeholder: " text" , rows: "1"
      .actions
        = form.submit "SEND"

.ui.animated.button
  .visible.content
    ボタンの文字が
  .hidden.content
    変わるんです！！

  
.ui.vertical.animated.button
  .visible.content
    今日の雨のように
  .hidden.content
    上から降ってきます

app/views/posts/show.html.haml
.wrapper
  = render "side_bar"

.main-message
  .main-message__tag-search
    = form_tag('/search', method: :get, class: 'main-message__tag-search__search-form') do
      %input.search-form__input{name: "keyword", placeholder: " 検索したい投稿を入力", type: "text", value: ""}
      %button.btn-search{title: "検索", type: "submit"}
        = icon('fas fa-search', class: "main-message__tag-search__search-form__icon")
  .main-message__contents
    = render @post
    .o3comments
      %h4
        ＜コメント一覧＞
        - @comments.each do |comment|
          %p
            -# = link_to posts_path do
            = comment.user.name
            = comment.text
            = image_tag comment.image.url, class: 'o3o3' if comment.image.present?
            
  -# .main-message__commentCreate
  -#   - if current_user
  -#     = form_with model: [@post, @comment], local: true do |f|
  -#       = f.text_field :text, class: 'nm__o3comfield'
  -#       .nm__o3base
  -#         = f.label :image, class: 'nm__o3base__maskImage' do
  -#           = icon('fas', 'camera', class: 'nm__o3base__maskImage__miIcon')
  -#           = f.file_field :image, class: 'nm__o3base__maskImage__hidden'
  -#       = f.submit "コメントする", class: "nm__submit"
  -#   - else
  -#     %strong
  -#       %p
  -#         ※※※ コメントの投稿には新規登録/ログインが必要です ※※※

  .main-message__commentCreate
    ＜コメント入力欄＞
    - if current_user
      = form_with model: [@post, @comment], local: true do |f|
        = f.text_field :text, class: 'nm__o3comfield'
        .nm__o3base2
          = f.label :image, class: 'nm__o3base2__maskImage' do
            = icon('fas', 'camera', class: 'nm__o3base2__maskImage__miIcon')
            = f.file_field :image, class: 'nm__o3base2__maskImage__hidden'
        = f.submit "送信", class: "nm__submit"
    - else
      %strong
        %p
          ※※※ コメントの投稿には新規登録/ログインが必要です ※※※

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'